language: python

python:
 - "2.7"

cache: pip

install:
 - "pip install -r UnitTest/requirements.txt"

before_script:
 - cp UnitTest/piNumber.txt -r WebPage/pages
 - cp UnitTest/numSensors.txt -r WebPage/pages
 - cp UnitTest/newPeakTimes.txt -r WebPage/pages
 - cp UnitTest/reset.txt -r WebPage/pages
 - cp UnitTest/sensorInfo.txt -r WebPage/pages
 - cp UnitTest/dataCollectionSet.txt -r WebPage/pages
 - mkdir /home/travis/build/MatthewHeun/Data/
 - mkdir /home/travis/build/MatthewHeun/Data/Pi_-1_Raw/
 - mkdir /home/travis/build/MatthewHeun/Data/Pi_-1_Summary/
 - mkdir /home/travis/build/MatthewHeun/Data/Pi_-1_Raw/Sensor1/
 - mkdir /home/travis/build/MatthewHeun/Data/Pi_-1_Summary/Sensor1/
 - mkdir /home/travis/build/MatthewHeun/Data/Pi_-1_Raw/Sensor2/
 - mkdir /home/travis/build/MatthewHeun/Data/Pi_-1_Summary/Sensor2/
 - mkdir /home/travis/build/MatthewHeun/Data/Pi_-1_Raw/Sensor3/
 - mkdir /home/travis/build/MatthewHeun/Data/Pi_-1_Summary/Sensor3/
 
script:
 - python Python/TestAnalyze.py
 
notifications:
  email: false
  
 