language:
 - python
 - bash

python:
 - "2.7"

cache: 
 - pip

before_install:
 - chmod ugo+x prepUnitTest.sh
 - bash prepUnitTest.sh
 
install:
 - "pip install -r UnitTest/requirements.txt"
 - sudo apt-get install python-pip
 - sudo apt-get install xrdp
 - sudo easy_install pytz
 
script:
 - bash prepUnitTest.sh
 - python Python/TestPython.py
 
notifications:
  email: false
 