language:
 - python
 - bash

python:
 - "2.7"

cache: pip

install:
 - "pip install -r UnitTest/requirements.txt"

script:
 - chmod ugo+x prepUnitTest.sh
 - bash prepUnitTest.sh
 - python Python/TestAnalyze.py
 
notifications:
  email: false
  
 