language: python

python:
 - "2.7"

cache: pip

install:
 - "pip install -r UnitTest/requirements.txt"

before_script:
 - chmod ugo+x prepUnitTest.sh
 - .prepUnitTest.sh
 
 
script:
 - python Python/TestAnalyze.py
 
notifications:
  email: false
  
 