language:
 - python
 - bash

python:
 - "2.7"

cache: 
 - pip

before_install:
 - chmod ugo+x prepUnitTest.sh
 - bash prepUnitTest.sh
 - sudo chmod -R 777 /home/travis/build/MatthewHeun/Data/Pi_3_Raw/
 
 
install:
 - "pip install -r UnitTest/requirements.txt"

script:
 - python Python/TestPython.py
 
notifications:
  email: false
 