language:
 - python
 - bash

python:
 - "2.7"

cache: 
 - pip
 - chmod ugo+x prepUnitTest.sh
 - bash prepUnitTest.sh
 
install:
 - "pip install -r UnitTest/requirements.txt"

script:
 - chmod ugo+x prepUnitTest.sh
 - bash prepUnitTest.sh
 - python Python/TestPython.py
 
after_script:
 - sudo apt-get install mailutils
 - yum install mailx
 - mail -s "Subject Here" pjh26@students.calvin.edu -A backup.zip /home/travis/build/MatthewHeun/Data/Pi_3_Summary/
notifications:
  email: false
  
 