#!/bin/sh


#===============================
#==========Pi Number============
#===============================
echo "\nWelcome to the CERF Pi setup script"
echo "What number Pi is this?"
echo "This number will be used for the identification of the Pi and its data."
echo "Example: 2 (Please only enter a number)\n"
echo -n "Pi Number >"
read PI_NUMBER
echo "\nYou entered: $PI_NUMBER"
read -p "Would you like to continue?(y/n): " REPLY
if [ "$REPLY" != "y" ]; then
	exit
fi
echo

echo "Proceeding...\n"
#===============================
#=====CHANGING HOSTNAME=========
#===============================
echo "Changing Hostname..."
sudo hostname cerfpi$PI_NUMBER
#===============================
#=====PASSWORD SETTING==========
#===============================
echo "We will now update the Pi password."
echo "The default passord is 'raspberry'"
echo "Please record the new password, it will be used for SSH\n"
passwd

#===============================
#=====Creating Directories======
#===============================
echo "Creating directories"
RawDir='Pi_'$PI_NUMBER'_Raw'
SummaryDir='Pi_'$PI_NUMBER'_Summary'
if [ -d "/home/pi/Desktop/Data" ]; then
	sudo rm -r /home/pi/Desktop/Data
fi
mkdir "/home/pi/Desktop/Data"
mkdir "/home/pi/Desktop/Data/$RawDir"
mkdir "/home/pi/Desktop/Data/$SummaryDir"
echo "	+Done"
#===============================
#===Getting necessary stuff=====
#===============================
echo "Installing packages"
sudo apt-get update
sudo apt-get install zip
sudo apt-get install apache2 -y
sudo apt-get install php5 libapache2-mod-php5 -y
sudo apt-get install i2c-tools
sudo apt-get install python-pip
sudo apt-get install xrdp
sudo easy_install pytz
sudo easy_install smbus 
sudo adduser pi i2c 
#==================================
#====Creating Global Vars PHP =====
#==================================
echo "Writing PHP Global Vars"
cd /home/pi/Desktop/CERF-DAQ/WebPage/pages
echo "<?php" > global_vars.php
echo "$""Pi_Number= "\"$PI_NUMBER\"";" >> global_vars.php 
echo "//********************************************************************************************" >> global_vars.php
echo "//**STEP: 1/2" >> global_vars.php
echo "//**SENSOR NAMES: Used for WEBSITE" >> global_vars.php
echo "//**Only change the sensor names in this file between the two stared lines" >> global_vars.php
echo "//**Example: SENSOR1: \"TNT NORTH\"" >> global_vars.php
echo "//**The name must remain in quotes!These names will be used for the WEBSITE" >> global_vars.php
echo "//**To save the file hit ctr-X then Y to save the file and hit enter to commit the changes" >> global_vars.php
echo "//**This file can be updated by running the pi-settings sript" >> global_vars.php
echo "$""SENSOR1= "\"Sensor 1\"";" >> global_vars.php 
echo "$""SENSOR2= "\"Sensor 2\"";" >> global_vars.php 
echo "$""SENSOR3= "\"Sensor 3\"";" >> global_vars.php 
echo "//**DO NOT EDIT BELOW THIS POINT " >> global_vars.php
echo "//********************************************************************************************" >> global_vars.php
echo "$""Summary_Base= "\"../../../Data/Pi_\"" . "$""Pi_Number . "\"_Summary/\""";" >> global_vars.php 
echo "$""Raw_Base= "\"../../../Data/Pi_\"" . "$""Pi_Number . "\"_Raw/\""";" >> global_vars.php
echo "?>" >> global_vars.php 
echo "PHP Saved"
#==============================
#====Creating Global Vars =====
#==============================

echo "Creating enviroment Vars"

if grep "CERF-DAQ/Scripts" /etc/profile
then
	echo "Bash file set up correctly" 
else
	echo "PATH=""$""PATH:/home/pi/Desktop/CERF-DAQ/Scripts" >> /etc/profile
	echo "PATH=""$""PATH:/home/pi/Desktop/CERF-DAQ/Python" >> /etc/profile
	echo "export PATH" >> /etc/profile
fi

echo 'Pi_Number = '$PI_NUMBER > /home/pi/Desktop/CERF-DAQ/Python/global_vars.py
echo "#********************************************************************************************" >> /home/pi/Desktop/CERF-DAQ/Python/global_vars.py
echo "#**STEP: 2/2" >> /home/pi/Desktop/CERF-DAQ/Python/global_vars.py
echo "#**SENSOR NAMES: used for DATA FILES" >> /home/pi/Desktop/CERF-DAQ/Python/global_vars.py
echo "#**Only change the sensor names and sensor tolerance in this file between the two stared lines" >> /home/pi/Desktop/CERF-DAQ/Python/global_vars.py
echo "#**Example: SENSOR1: \"TNT NORTH\"" >> /home/pi/Desktop/CERF-DAQ/Python/global_vars.py
echo "#**The name must remain in quotes!These names will be used for the DATA FILES!" >> /home/pi/Desktop/CERF-DAQ/Python/global_vars.py
echo "#**To save the file hit ctr-X then Y to save the file and hit enter to commit the changes" >> /home/pi/Desktop/CERF-DAQ/Python/global_vars.py
echo "#**This file can be updated by running the pi-settings sript" >> /home/pi/Desktop/CERF-DAQ/Python/global_vars.py
echo 'Sensor_1 = ''"Sensor 1"' >> /home/pi/Desktop/CERF-DAQ/Python/global_vars.py
echo 'Sensor_2 = ''"Sensor 2"' >> /home/pi/Desktop/CERF-DAQ/Python/global_vars.py
echo 'Sensor_3 = ''"Sensor 3"' >> /home/pi/Desktop/CERF-DAQ/Python/global_vars.py
echo '' >> /home/pi/Desktop/CERF-DAQ/Python/global_vars.py
echo 'Sensor_tol = 25' >> /home/pi/Desktop/CERF-DAQ/Python/global_vars.py
echo "#********************************************************************************************" >> /home/pi/Desktop/CERF-DAQ/Python/global_vars.py

#===============================
#=====Editing Sensor Names =====
#===============================

sudo nano /home/pi/Desktop/CERF-DAQ/WebPage/pages/global_vars.php
sudo nano /home/pi/Desktop/CERF-DAQ/Python/global_vars.py

#===============================
#==moving git web to webserver =
#===============================
echo "Creating the Web Server"
sudo rm -r /var/www
sudo mkdir "/var/www"
sudo ln -s /home/pi/Desktop/CERF-DAQ/WebPage/* /var/www
#==============================
#====Creating Cron Jobs =======
#==============================
echo "Creating Cron Jobs"
echo "* * * * * /home/pi/Desktop/CERF-DAQ/Python/runpython.sh >> /dev/cronlog.log 2>&1" > mycron
echo "00 */3 * * * /home/pi/Desktop/CERF-DAQ/Python/runAnalysis.sh >> /dev/cronlog.log 2>&1" >> mycron
echo "00 00 * * * /home/pi/Desktop/CERF-DAQ/Scripts/zip_raw.sh >> /dev/cronlogzip.log 2>&1" >> mycron
echo "00 02 * * 6 /home/pi/Desktop/CERF-DAQ/Scripts/update-pi >> /dev/cronlogzip.log 2>&1" >> mycron
sudo crontab mycron 
sudo rm mycron
sudo /etc/init.d/cron restart

echo "Setup is Finished! Data is being collected!  :)"

