#!/bin/bash

$PI_NUMBER=$0


#===============================
#==========Pi Number============
#===============================
echo $'\nWelcome to the CERF Pi setup script'
echo "What number Pi is this?"
echo "This number will be used for the identification of the Pi and its data."
echo $'Example: 2 (Please only enter a number)\n'
echo -n "Pi Number >"
read PI_NUMBER
echo -e "\nYou entered: $PI_NUMBER"
read -p "Would you like to continue?(y/n): " REPLY
if [ "$REPLY" != "y" ]; then
	exit
fi
echo

export PI_NUMBER

echo $PI_NUMBER > /home/pi/Desktop/CERF-DAQ/WebPage/pages/piNumber.txt
echo 0 > /home/pi/Desktop/CERF-DAQ/WebPage/pages/numSensors.txt
echo 0 > /home/pi/Desktop/CERF-DAQ/WebPage/pages/sensorInfo.txt
echo 0 > /home/pi/Desktop/CERF-DAQ/WebPage/pages/reset.txt
echo 1 > /home/pi/Desktop/CERF-DAQ/WebPage/pages/zipHealth.txt
echo 0 > /home/pi/Desktop/CERF-DAQ/WebPage/pages/zipStatus.txt
echo 1 > /home/pi/Desktop/CERF-DAQ/WebPage/pages/updateHealth.txt
echo 0 > /home/pi/Desktop/CERF-DAQ/WebPage/pages/onPeakOffPeakTime.txt
echo '0' > /home/pi/Desktop/CERF-DAQ/WebPage/pages/newPeakTimes.txt
echo '6' >> /home/pi/Desktop/CERF-DAQ/WebPage/pages/newPeakTimes.txt
echo '12' >> /home/pi/Desktop/CERF-DAQ/WebPage/pages/newPeakTimes.txt
echo '14' >> /home/pi/Desktop/CERF-DAQ/WebPage/pages/newPeakTimes.txt
echo '17' >> /home/pi/Desktop/CERF-DAQ/WebPage/pages/newPeakTimes.txt
echo '19' >> /home/pi/Desktop/CERF-DAQ/WebPage/pages/newPeakTimes.txt
echo '23' >> /home/pi/Desktop/CERF-DAQ/WebPage/pages/newPeakTimes.txt
echo '14' >> /home/pi/Desktop/CERF-DAQ/WebPage/pages/newPeakTimes.txt
echo '16' >> /home/pi/Desktop/CERF-DAQ/WebPage/pages/newPeakTimes.txt
echo '19' >> /home/pi/Desktop/CERF-DAQ/WebPage/pages/newPeakTimes.txt
echo '21' >> /home/pi/Desktop/CERF-DAQ/WebPage/pages/newPeakTimes.txt
echo '23' >> /home/pi/Desktop/CERF-DAQ/WebPage/pages/newPeakTimes.txt
echo '1' >> /home/pi/Desktop/CERF-DAQ/WebPage/pages/newPeakTimes.txt
echo '2' >> /home/pi/Desktop/CERF-DAQ/WebPage/pages/newPeakTimes.txt
echo '3' >> /home/pi/Desktop/CERF-DAQ/WebPage/pages/newPeakTimes.txt
echo '4' >> /home/pi/Desktop/CERF-DAQ/WebPage/pages/newPeakTimes.txt
echo '5' >> /home/pi/Desktop/CERF-DAQ/WebPage/pages/newPeakTimes.txt
chmod ugo+rwx /home/pi/Desktop/CERF-DAQ/ -R

echo "Starting i2c...."
echo snd-bcm2835 > /etc/modules
echo i2c-bcm2708 >> /etc/modules
echo i2c-dev >> /etc/modules
echo "i2c initialized"

echo $"Proceeding...\n"


#===============================
#=====CHANGING HOSTNAME=========
#===============================
echo "Changing Hostname..."
#echo "cerfpi$PI_NUMBER" > /etc/hostname 


#===============================
#=====PASSWORD SETTING==========
#===============================
echo "We will now update the Pi password."
echo "The default passord is 'raspberry'"
echo $"Please record the new password, it will be used for SSH\n"
read -p "Would you like to change the user password?(y/n): " PASSCHANGE
if [ "$PASSCHANGE" = "y" ]; then
	passwd pi
fi
echo "proceeding"


#===============================
#=====Creating Directories======
#===============================
echo "Creating directories"
RawDir='Pi_'$PI_NUMBER'_Raw'
SummaryDir='Pi_'$PI_NUMBER'_Summary'
if [ -d "/home/pi/Desktop/Data" ]; then
	sudo rm -r /home/pi/Desktop/Data
fi
mkdir "/home/pi/Desktop/Data"
mkdir "/home/pi/Desktop/Data/$RawDir"
mkdir "/home/pi/Desktop/Data/$SummaryDir"
chmod ugo+rwx /home/pi/Desktop/Data -R
echo "	+Done"


#===============================
#===Getting necessary stuff=====
#===============================
echo "Installing packages"
sudo apt-get update
sudo apt-get install zip
sudo apt-get install apache2 -y
sudo apt-get install php
sudo apt-get install i2c-tools
sudo apt-get install python-pip
sudo apt-get install xrdp
sudo easy_install pytz
sudo apt-get install python-smbus 
sudo adduser pi i2c 
sudo pip install adafruit-ads1x15
echo "	+Done"


#==============================
#====Creating Global Vars======
#==============================

echo "Creating enviroment Vars"

if grep "CERF-DAQ/Scripts" /etc/profile
then
	echo "Bash file set up correctly" 
else
	echo "PATH=""$""PATH:/home/pi/Desktop/CERF-DAQ/Scripts" >> /etc/profile
	echo "PATH=""$""PATH:/home/pi/Desktop/CERF-DAQ/Python" >> /etc/profile
	echo "export PATH" >> /etc/profile
fi
echo "	+Done"


#===============================
#==moving git web to webserver =
#===============================
echo "Creating the Web Server"
sudo rm -rf /var/www
sudo mkdir "/var/www"
sudo ln -s /home/pi/Desktop/CERF-DAQ/WebPage/* /var/www
echo "	+Done"


#==============================
#=====Creating Cron Jobs=======
#==============================
echo "Creating Cron Jobs"
echo "#m h dom mon dow  command" > mycron
echo "* * * * * /home/pi/Desktop/CERF-DAQ/Python/runpython.sh >> /dev/GetDataCron.log 2>&1" >> mycron
echo "00 10 * * * /home/pi/Desktop/CERF-DAQ/Python/runAnalysis.sh >> /dev/AnalysisCron.log 2>&1" >> mycron
echo "00 01 * * * /home/pi/Desktop/CERF-DAQ/Scripts/zip-data.sh >> /dev/ZipCron.log 2>&1" >> mycron
echo "00 02 * * 6 /home/pi/Desktop/CERF-DAQ/Scripts/update-pi.sh >> /dev/UpdatePiCron.log 2>&1" >> mycron
echo "00 00 * * *  sudo reboot" >> mycron
sudo crontab mycron 
sudo rm mycron
sudo /etc/init.d/cron restart
echo "	+Done"


#==============================
#=====Updating Pi Kernel=======
#==============================
echo "Updating the Pi Kernel Version"
echo "The current version is:"
uname -a
sudo apt-get upgrade
echo "	+Done"


#==============================
#======Configuring Wifi========
#==============================
echo -e '\n\n'
echo "Configuring the Wifi"
read -p "Would you like to setup wifi?(y/n): " REPLY
if [ "$REPLY" == "y" ]; then
	/bin/bash /home/pi/Desktop/CERF-DAQ/writeSupplicant
fi
echo "proceeding"

#==============================
#=====Changing Wifi Dir.=======
#==============================
echo "Changing wifi directory"
truncate -s 0 /etc/apache2/sites-enabled/000-default.conf
/bin/bash /home/pi/Desktop/CERF-DAQ/writeWebDirectory
echo "	+Done"

#==============================
#========Upgrading Pi==========
#==============================
echo "Upgrading the pi to the latest kernel version"
sudo apt-get upgrade
echo "	+Done"

#==============================
#========Restarting Pi=========
#==============================
echo "Setup is completed" 
echo "The pi will now reboot and is ready to start taking data"
echo "You will be disconected"
sudo reboot 


