#!/bin/sh


#===============================
#==========Pi Number============
#===============================
echo "\nWelcome to the CERF Pi setup script"
echo "What number Pi is this?"
echo "This number will be used for the identification of the Pi and its data."
echo "Example: 2 (Please only enter a number)\n"
echo -n "Pi Number >"
read PI_NUMBER
echo "\nYou entered: $PI_NUMBER"
read -p "Would you like to continue?(y/n): " REPLY
if [ "$REPLY" != "y" ]; then
	exit
fi
echo

echo "Proceeding...\n"
#===============================
#=====CHANGING HOSTNAME=========
#===============================
echo "Changing Hostname..."
#echo "cerfpi$PI_NUMBER" > /etc/hostname 
#===============================
#=====PASSWORD SETTING==========
#===============================
echo "We will now update the Pi password."
echo "The default passord is 'raspberry'"
echo "Please record the new password, it will be used for SSH\n"
read -p "Would you like to change the user password?(y/n): " PASSCHANGE
if [ "$PASSCHANGE" = "y" ]; then
	passwd pi
fi
echo "proceeding"

#===============================
#=====Creating Directories======
#===============================
echo "Creating directories"
RawDir='Pi_'$PI_NUMBER'_Raw'
SummaryDir='Pi_'$PI_NUMBER'_Summary'
if [ -d "/home/pi/Desktop/Data" ]; then
	sudo rm -r /home/pi/Desktop/Data
fi
mkdir "/home/pi/Desktop/Data"
mkdir "/home/pi/Desktop/Data/$RawDir"
mkdir "/home/pi/Desktop/Data/$SummaryDir"
echo "	+Done"
#===============================
#===Getting necessary stuff=====
#===============================
echo "Installing packages"
sudo apt-get update
sudo apt-get install zip
sudo apt-get install apache2 -y
sudo apt-get install php5 libapache2-mod-php5 -y
sudo apt-get install i2c-tools
sudo apt-get install python-pip
sudo apt-get install xrdp
sudo easy_install pytz
sudo easy_install smbus 
sudo adduser pi i2c 
#==============================
#====Creating Global Vars =====
#==============================

echo "Creating enviroment Vars"

if grep "CERF-DAQ/Scripts" /etc/profile
then
	echo "Bash file set up correctly" 
else
	echo "PATH=""$""PATH:/home/pi/Desktop/CERF-DAQ/Scripts" >> /etc/profile
	echo "PATH=""$""PATH:/home/pi/Desktop/CERF-DAQ/Python" >> /etc/profile
	echo "export PATH" >> /etc/profile
fi

echo 'Pi_Number = '$PI_NUMBER > /home/pi/Desktop/CERF-DAQ/Python/user_input.py
echo "#********************************************************************************************" >> /home/pi/Desktop/CERF-DAQ/Python/user_input.py
echo "#**SENSOR NAMES: used for DATA FILES and WEBSITE" >> /home/pi/Desktop/CERF-DAQ/Python/user_input.py
echo "#**Only change the sensor names and sensor tolerance in this file between the two starred lines" >> /home/pi/Desktop/CERF-DAQ/Python/user_input.py
echo "#**Example: SENSOR1: \"TNT NORTH\"" >> /home/pi/Desktop/CERF-DAQ/Python/user_input.py
echo "#**The name must remain in quotes!These names will be used for the DATA FILES and website" >> /home/pi/Desktop/CERF-DAQ/Python/user_input.py
echo "#**To save the file hit ctr-X then Y to save the file and hit enter to commit the changes" >> /home/pi/Desktop/CERF-DAQ/Python/user_input.py
echo "#**This file can be updated by running the pi-settings sript" >> /home/pi/Desktop/CERF-DAQ/Python/user_input.py

echo ''>> /home/pi/Desktop/CERF-DAQ/Python/user_input.py
echo 'Number_of_Temperature_and_Light_Sensors = 3  #The number of temperature and light sensors connected to the pi' >> /home/pi/Desktop/CERF-DAQ/Python/user_input.py
echo ''>> /home/pi/Desktop/CERF-DAQ/Python/user_input.py

echo "#**Enter sensor names here!!" >> /home/pi/Desktop/CERF-DAQ/Python/user_input.py
echo 'Sensor_1 = ''"Sensor_1"' >> /home/pi/Desktop/CERF-DAQ/Python/user_input.py
echo 'Sensor_2 = ''"Sensor_2"' >> /home/pi/Desktop/CERF-DAQ/Python/user_input.py
echo 'Sensor_3 = ''"Sensor_3"' >> /home/pi/Desktop/CERF-DAQ/Python/user_input.py
echo 'Sensor_4 = ''"Sensor_4"' >> /home/pi/Desktop/CERF-DAQ/Python/user_input.py
echo 'Sensor_5 = ''"Sensor_5"' >> /home/pi/Desktop/CERF-DAQ/Python/user_input.py
echo 'Sensor_6 = ''"Sensor_6"' >> /home/pi/Desktop/CERF-DAQ/Python/user_input.py
echo 'Sensor_7 = ''"Sensor_7"' >> /home/pi/Desktop/CERF-DAQ/Python/user_input.py
echo 'Sensor_8 = ''"Sensor_8"' >> /home/pi/Desktop/CERF-DAQ/Python/user_input.py
echo 'Sensor_9 = ''"Sensor_9"' >> /home/pi/Desktop/CERF-DAQ/Python/user_input.py
echo 'Sensor_10 = ''"Sensor_10"' >> /home/pi/Desktop/CERF-DAQ/Python/user_input.py
echo 'Sensor_11 = ''"Sensor_11"' >> /home/pi/Desktop/CERF-DAQ/Python/user_input.py
echo 'Sensor_12 = ''"Sensor_12"' >> /home/pi/Desktop/CERF-DAQ/Python/user_input.py
echo 'Sensor_13 = ''"Sensor_13"' >> /home/pi/Desktop/CERF-DAQ/Python/user_input.py
echo 'Sensor_14 = ''"Sensor_14"' >> /home/pi/Desktop/CERF-DAQ/Python/user_input.py
echo 'Sensor_15 = ''"Sensor_15"' >> /home/pi/Desktop/CERF-DAQ/Python/user_input.py
echo 'Sensor_16 = ''"Sensor_16"' >> /home/pi/Desktop/CERF-DAQ/Python/user_input.py
echo '' >> /home/pi/Desktop/CERF-DAQ/Python/user_input.py
echo 'Sensor_tol = 25   #any light reading below this value will be considered off' >> /home/pi/Desktop/CERF-DAQ/Python/user_input.py
echo 'PeakTime1 = 11    #hour in a 24 hour day' >> /home/pi/Desktop/CERF-DAQ/Python/user_input.py
echo 'PeakTime2 = 19    #hour in a 24 hour day' >> /home/pi/Desktop/CERF-DAQ/Python/user_input.py
echo '' >> /home/pi/Desktop/CERF-DAQ/Python/user_input.py

echo "#**Enter sensor types here!!" >> /home/pi/Desktop/CERF-DAQ/Python/user_input.py
echo '# Use either "Light" or "Temperature"' >> /home/pi/Desktop/CERF-DAQ/Python/user_input.py
echo 'Sensor_1_Type = "Light"' >> /home/pi/Desktop/CERF-DAQ/Python/user_input.py
echo 'Sensor_2_Type = "Light"' >> /home/pi/Desktop/CERF-DAQ/Python/user_input.py
echo 'Sensor_3_Type = "Light"' >> /home/pi/Desktop/CERF-DAQ/Python/user_input.py
echo 'Sensor_4_Type = "Light"' >> /home/pi/Desktop/CERF-DAQ/Python/user_input.py
echo 'Sensor_5_Type = "Light"' >> /home/pi/Desktop/CERF-DAQ/Python/user_input.py
echo 'Sensor_6_Type = "Light"' >> /home/pi/Desktop/CERF-DAQ/Python/user_input.py
echo 'Sensor_7_Type = "Light"' >> /home/pi/Desktop/CERF-DAQ/Python/user_input.py
echo 'Sensor_8_Type = "Light"' >> /home/pi/Desktop/CERF-DAQ/Python/user_input.py
echo 'Sensor_9_Type = "Light"' >> /home/pi/Desktop/CERF-DAQ/Python/user_input.py
echo 'Sensor_10_Type = "Light"' >> /home/pi/Desktop/CERF-DAQ/Python/user_input.py
echo 'Sensor_11_Type = "Light"' >> /home/pi/Desktop/CERF-DAQ/Python/user_input.py
echo 'Sensor_12_Type = "Light"' >> /home/pi/Desktop/CERF-DAQ/Python/user_input.py
echo 'Sensor_13_Type = "Light"' >> /home/pi/Desktop/CERF-DAQ/Python/user_input.py
echo 'Sensor_14_Type = "Light"' >> /home/pi/Desktop/CERF-DAQ/Python/user_input.py
echo 'Sensor_15_Type = "Light"' >> /home/pi/Desktop/CERF-DAQ/Python/user_input.py
echo 'Sensor_16_Type = "Light"' >> /home/pi/Desktop/CERF-DAQ/Python/user_input.py

echo "#**Enter occupancy sensor names here!!" >> /home/pi/Desktop/CERF-DAQ/Python/user_input.py
echo 'Number_of_Occupancy_Sensors = 4 #The number of occupancy sensors connected ot the pi' >> /home/pi/Desktop/CERF-DAQ/Python/user_input.py
echo 'Occupancy_1 = "Occupancy_1"' >> /home/pi/Desktop/CERF-DAQ/Python/user_input.py
echo 'Occupancy_2 = "Occupancy_2"' >> /home/pi/Desktop/CERF-DAQ/Python/user_input.py
echo 'Occupancy_3 = "Occupancy_3"' >> /home/pi/Desktop/CERF-DAQ/Python/user_input.py
echo 'Occupancy_4 = "Occupancy_4"' >> /home/pi/Desktop/CERF-DAQ/Python/user_input.py
echo 'Occupancy_5 = "Occupancy_5"' >> /home/pi/Desktop/CERF-DAQ/Python/user_input.py
echo 'Occupancy_6 = "Occupancy_6"' >> /home/pi/Desktop/CERF-DAQ/Python/user_input.py
echo 'Occupancy_7 = "Occupancy_7"' >> /home/pi/Desktop/CERF-DAQ/Python/user_input.py
echo 'Occupancy_8 = "Occupancy_8"' >> /home/pi/Desktop/CERF-DAQ/Python/user_input.py
echo 'Occupancy_9 = "Occupancy_9"' >> /home/pi/Desktop/CERF-DAQ/Python/user_input.py
echo 'Occupancy_10 = "Occupancy_10"' >> /home/pi/Desktop/CERF-DAQ/Python/user_input.py
echo 'Occupancy_11 = "Occupancy_11"' >> /home/pi/Desktop/CERF-DAQ/Python/user_input.py
echo 'Occupancy_12 = "Occupancy_12"' >> /home/pi/Desktop/CERF-DAQ/Python/user_input.py
echo 'Occupancy_13 = "Occupancy_13"' >> /home/pi/Desktop/CERF-DAQ/Python/user_input.py
echo 'Occupancy_14 = "Occupancy_14"' >> /home/pi/Desktop/CERF-DAQ/Python/user_input.py
echo 'Occupancy_15 = "Occupancy_15"' >> /home/pi/Desktop/CERF-DAQ/Python/user_input.py
echo 'Occupancy_16 = "Occupancy_16"' >> /home/pi/Desktop/CERF-DAQ/Python/user_input.py
echo "#********************************************************************************************" >> /home/pi/Desktop/CERF-DAQ/Python/user_input.py

#===============================
#=====Editing Sensor Names =====
#===============================

sudo nano /home/pi/Desktop/CERF-DAQ/Python/user_input.py
sudo python /home/pi/Desktop/CERF-DAQ/Python/global_vars_to_php.py

#===============================
#==moving git web to webserver =
#===============================
echo "Creating the Web Server"
sudo rm -r /var/www
sudo mkdir "/var/www"
sudo ln -s /home/pi/Desktop/CERF-DAQ/WebPage/* /var/www
#==============================
#====Creating Cron Jobs =======
#==============================
echo "Creating Cron Jobs"
echo "#m h dom mon dow  command" > mycron
echo "* * * * * /home/pi/Desktop/CERF-DAQ/Python/runpython.sh >> /dev/cronlog.log 2>&1" >> mycron
echo "00 01 * * * /home/pi/Desktop/CERF-DAQ/Python/runAnalysis.sh >> /dev/cronlog.log 2>&1" >> mycron
echo "00 00 * * * /home/pi/Desktop/CERF-DAQ/Scripts/zip_raw.sh >> /dev/cronlogzip.log 2>&1" >> mycron
echo "00 02 * * 6 /home/pi/Desktop/CERF-DAQ/Scripts/update-pi >> /dev/cronlogzip.log 2>&1" >> mycron
sudo crontab mycron 
sudo rm mycron
sudo /etc/init.d/cron restart
echo "Setup is completed" 
echo "The pi will now reboot and start taking data"
echo "You will be disconected"
sudo reboot 


