#!/bin/bash

echo '<VirtualHost *:80>' >> /etc/apache2/sites-enabled/000-default.conf
echo '	# The ServerName directive sets the request scheme, hostname and port that' >> /etc/apache2/sites-enabled/000-default.conf
echo '	# the server uses to identify itself. This is used when creating' >> /etc/apache2/sites-enabled/000-default.conf
echo '	# redirection URLs. In the context of virtual hosts, the ServerName' >> /etc/apache2/sites-enabled/000-default.conf
echo '	# specifies what hostname must appear in the request's Host: header to' >> /etc/apache2/sites-enabled/000-default.conf
echo '	# match this virtual host. For the default virtual host (this file) this' >> /etc/apache2/sites-enabled/000-default.conf
echo '	# value is not decisive as it is used at a last resort host regardless.' >> /etc/apache2/sites-enabled/000-default.conf
echo '	# However, you must set it for any further virtual host explicitly.' >> /etc/apache2/sites-enabled/000-default.conf
echo '	#ServerName www.example.com' >> /etc/apache2/sites-enabled/000-default.conf
echo '' >> /etc/apache2/sites-enabled/000-default.conf
echo '	ServerAdmin webmaster@localhost' >> /etc/apache2/sites-enabled/000-default.conf
echo '	DocumentRoot /var/www/' >> /etc/apache2/sites-enabled/000-default.conf
echo '' >> /etc/apache2/sites-enabled/000-default.conf
echo '	# Available loglevels: trace8, ..., trace1, debug, info, notice, warn,' >> /etc/apache2/sites-enabled/000-default.conf
echo '	# error, crit, alert, emerg.' >> /etc/apache2/sites-enabled/000-default.conf
echo '	# It is also possible to configure the loglevel for particular' >> /etc/apache2/sites-enabled/000-default.conf
echo '	# modules, e.g.' >> /etc/apache2/sites-enabled/000-default.conf
echo '	#LogLevel info ssl:warn' >> /etc/apache2/sites-enabled/000-default.conf
echo '' >> /etc/apache2/sites-enabled/000-default.conf
echo '	ErrorLog ${APACHE_LOG_DIR}/error.log' >> /etc/apache2/sites-enabled/000-default.conf
echo '	CustomLog ${APACHE_LOG_DIR}/access.log combined' >> /etc/apache2/sites-enabled/000-default.conf
echo '' >> /etc/apache2/sites-enabled/000-default.conf
echo '	# For most configuration files from conf-available/, which are' >> /etc/apache2/sites-enabled/000-default.conf
echo '	# enabled or disabled at a global level, it is possible to' >> /etc/apache2/sites-enabled/000-default.conf
echo '	# include a line for only one particular virtual host. For example the' >> /etc/apache2/sites-enabled/000-default.conf
echo '	# following line enables the CGI configuration for this host only' >> /etc/apache2/sites-enabled/000-default.conf
echo '	# after it has been globally disabled with "a2disconf".' >> /etc/apache2/sites-enabled/000-default.conf
echo '	#Include conf-available/serve-cgi-bin.conf' >> /etc/apache2/sites-enabled/000-default.conf
echo '</VirtualHost>' >> /etc/apache2/sites-enabled/000-default.conf
echo '' >> /etc/apache2/sites-enabled/000-default.conf
echo '# vim: syntax=apache ts=4 sw=4 sts=4 sr noet' >> /etc/apache2/sites-enabled/000-default.conf
echo '' >> /etc/apache2/sites-enabled/000-default.conf

echo " +Done"
